Fix NPE in EphemeralFileChannel when file is unlinked ()
When applied an EphemeralFileChannel can keep reading an unlinked file, instead of dying with

```
java.lang.NullPointerException: Cannot invoke "java.util.SortedMap.getOrDefault(Object, Object)" because "this.sectors" is null

	at org.neo4j.io.fs.EphemeralDynamicByteBuffer.get(EphemeralDynamicByteBuffer.java:119)
	at org.neo4j.io.fs.EphemeralFileData.read(EphemeralFileData.java:69)
	at org.neo4j.io.fs.EphemeralFileChannel.read(EphemeralFileChannel.java:80)
	at org.neo4j.io.fs.StoreFileChannel.readAll(StoreFileChannel.java:211)
```

This emulates how file descriptors remain valid on Linux after the file has been unlinked.