Fix transaction memory tracker concurrent access in SPD ()
Before this change, we were sharing the non-thread-safe
`LocalMemoryTracker` with multiple threads sending shards requests
concurrently. This could lead to some misaccounted bytes that, in turn,
only become a problem when resetting the transaction state and
attempting to release those from the transaction memory pool, leading to
this sort of exception:

```
java.lang.AssertionError: Heap memory leak. Expecting all allocated memory to be released, but still has 2097152
  at org.neo4j.kernel.impl.api.TransactionMemoryPool.reset(TransactionMemoryPool.java:182)
  at org.neo4j.kernel.impl.api.TransactionMemoryPool.close(TransactionMemoryPool.java:70)
  at org.neo4j.kernel.impl.api.KernelTransactionImplementation.dispose(KernelTransactionImplementation.java:1723)
  at org.neo4j.kernel.impl.api.KernelTransactions#GlobalKernelTransactionPool.dispose(KernelTransactions.java:661)
  at org.neo4j.kernel.impl.api.KernelTransactions#MonitoredTransactionPool.dispose(KernelTransactions.java:696)
  at org.neo4j.kernel.impl.api.KernelTransactions#MonitoredTransactionPool.dispose(KernelTransactions.java:666)
  at org.neo4j.kernel.impl.api.KernelTransactionImplementation.close(KernelTransactionImplementation.java:1225)
  at org.neo4j.kernel.impl.coreapi.TransactionImpl.safeTerminalOperation(TransactionImpl.java:366)
  at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:202)
  at org.neo4j.kernel.impl.coreapi.TransactionImpl.commit(TransactionImpl.java:197)
  at com.neo4j.cypher.internal.javacompat.DeleteEntityStressIT.tearDown(DeleteEntityStressIT.java:37)
  at com.neo4j.cypher.internal.javacompat.DeleteEntityStressIT.race(DeleteEntityStressIT.java:65)
  at com.neo4j.cypher.internal.javacompat.DeleteNodeStressIT.shouldBeAbleToSetPropertiesWhileDeletingNode(DeleteNodeStressIT.java:61)
``` 

Because we would be under releasing from the memory tracking. 

Since the transaction memory pool is actually thread safe itself the
simplest solution is to use a different `LocalMemoryTracker` for each
potential thread (note: each shard request isn't necessarily running on
a different thread, it might be).

---------

Co-authored-by: Agent Smith <103414894+neo4jagentsmith[bot]@users.noreply.github.com>