Spd parse exception if index population fails on a property shard ()
When we try to create an uniqueness index and the index population fails
on a property shard we only get the failure information in string
format. Before we just wrapped that error string in a new exception but
that did not display the correct information to the users. To display
which entities and property values that caused the failure we have to
parse the string and create a new `IndexEntryConflictException`

Previously we would print
```
org.neo4j.driver.exceptions.DatabaseException: Unable to create Constraint( name='constraint_5b5ebd5a', type='NODE PROPERTY UNIQUENESS', schema=(:A {id}) ):
Failed to populate index Index( id=2, name='constraint_5b5ebd5a', type='RANGE', schema=(:A {id}), indexProvider='range-1.0' ). Note that only the first found violation is shown.
```

Now we print (and the entity ids printed are the graph shard ids)
```
org.neo4j.driver.exceptions.DatabaseException: Unable to create Constraint( name='constraint_5b5ebd5a', type='NODE PROPERTY UNIQUENESS', schema=(:A {id}) ):
Both Node(0) and Node(5) have the label `A` and ( Long(0) ). Note that only the first found violation is shown.
```