Graph Engine: Write startup errors into `VirtualGraphLogger` and categorize errors. ()
This change adds a set of
`com.neo4j.graphengine.exception.GraphEngineErrors`, that indicates
either configuration or connection errors.

They are ultimately caught in the `EnterpriseEditionModule`. In there,
they are logged to
`org.neo4j.logging.log4j.LoggerTarget.VIRTUAL_GRAPH_LOGGER`. That logger
will as of now go into `debug.log` without any further configuration.
Based on the type of the error, markers are chosen to indicate the
specific problem (configuration or connectivity). Markers will be
available when `internal.server.logs.internal_markers.enabled` is set to
`true`.

Eventually, we can do more logging, i.e. the `JdbcSlottedPipe` or more
general, in the runtime. This is out of scope for this commit, which
particularly closes cge-484 so that the operator can pick up startup
errors.

In console mode, errors will appear like that:

```
2026-04-28 13:34:47.174+0000 ERROR Failed to start Neo4j on localhost:7474.
com.neo4j.dbms.edition.VirtualGraphStartupException: Virtual graph could not be started due to a connection problem
Caused by: com.neo4j.graphengine.schema.spi.GraphEngineError#GraphEngineException#GraphEngineConnectionException: Could not initialize connection pool (IO Error: Could not set lock on file "/Users/msimons/Projects/work/neo-technology/ge-test-data/puppygraph-benchmark/puppygraph-benchmark.duckdb": Conflicting lock is held in /opt/homebrew/Cellar/duckdb/1.5.0/bin/duckdb (PID 21824) by user msimons. See also https://duckdb.org/docs/stable/connect/concurrency)
	at com.neo4j.graphengine.data_source_providers.AbstractDataSourceProvider.createDataSource(AbstractDataSourceProvider.java:116)
	at com.neo4j.graphengine.configuration.EagerGraphEngineConfigurationFactory.createConfiguration(EagerGraphEngineConfigurationFactory.java:80)
	at com.neo4j.dbms.edition.EnterpriseEditionModule.lambda#startVirtualGraph#8(EnterpriseEditionModule.java:615)
...
Caused by: java.sql.SQLException: IO Error: Could not set lock on file "/Users/msimons/Projects/work/neo-technology/ge-test-data/puppygraph-benchmark/puppygraph-benchmark.duckdb": Conflicting lock is held in /opt/homebrew/Cellar/duckdb/1.5.0/bin/duckdb (PID 21824) by user msimons. See also https://duckdb.org/docs/stable/connect/concurrency
...
```

In the structured log by default like this:

```json
{
  "time": "2026-04-28 13:34:47.172+0000",
  "level": "ERROR",
  "marker": {
    "parents": [
      "VIRTUAL_GRAPH"
    ],
    "name": "CONNECTION"
  },
  "category": "VirtualGraphLogger",
  "message": "Virtual graph could not be started: Could not initialize connection pool (IO Error: Could not set lock on file \"/Users/msimons/Projects/work/neo-technology/ge-test-data/puppygraph-benchmark/puppygraph-benchmark.duckdb\": Conflicting lock is held in /opt/homebrew/Cellar/duckdb/1.5.0/bin/duckdb (PID 21824) by user msimons. See also https://duckdb.org/docs/stable/connect/concurrency)",
  "stacktrace": "a stacktrace"
}
```

```json
{
  "time": "2026-04-28 13:38:19.266+0000",
  "level": "ERROR",
  "marker": {
    "parents": [
      "VIRTUAL_GRAPH"
    ],
    "name": "CONNECTION"
  },
  "category": "VirtualGraphLogger",
  "message": "Virtual graph could not be started: Could not initialize connection pool (ORA-01017: invalid credential or not authorized; logon denied\n\nhttps://docs.oracle.com/error-help/db/ora-01017/)",
  "stacktrace": "ooops"
}
```

A configuration error will carry a sensible message:

```
Caused by: com.neo4j.graphengine.schema.spi.GraphEngineError#GraphEngineException#GraphEngineConfigurationException: secret.json is not a valid JSON file
	at com.neo4j.graphengine.configuration.EagerGraphEngineConfigurationFactory.createConfiguration(EagerGraphEngineConfigurationFactory.java:97)
	at com.neo4j.dbms.edition.EnterpriseEditionModule.lambda#startVirtualGraph#8(EnterpriseEditionModule.java:615)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.neo4j.graphdb.factory.module.edition.AbstractEditionModule.tryResolveOrCreate(AbstractEditionModule.java:256)
	at com.neo4j.dbms.edition.EnterpriseEditionModule.startVirtualGraph(EnterpriseEditionModule.java:605)
	at com.neo4j.dbms.edition.EnterpriseEditionModule.<init>(EnterpriseEditionModule.java:580)
	at com.neo4j.dbms.edition.EnterpriseEditionModule.<init>(EnterpriseEditionModule.java:395)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:141)
```

```json
{
  "time": "2026-04-28 13:43:36.756+0000",
  "level": "ERROR",
  "marker": {
    "parents": [
      "VIRTUAL_GRAPH"
    ],
    "name": "CONFIG"
  },
  "category": "VirtualGraphLogger",
  "message": "Virtual graph could not be started: secret.json is not a valid JSON file",
  "stacktrace": "oops"
}
```

```json
{
  "time": "2026-04-28 14:05:57.709+0000",
  "level": "ERROR",
  "marker": {
    "parents": [
      "VIRTUAL_GRAPH"
    ],
    "name": "CONFIG"
  },
  "category": "VirtualGraphLogger",
  "message": "Virtual graph could not be started: schema.json contains invalid mappings: Column `movie_actors`.`perxson_id` was not found in the remote database",
  "stacktrace": "ops"
}
```

---------

Signed-off-by: Michael Simons <michael.simons@neo4j.com>