ConstraintViolationTransactionFailureException: use cause GQL status
This should cover KNL-064
(as well as others that get wrapped in this exception).