Adjust UnixDomainSocketSchedulerIT ()
The `shouldProvideDedicatedPoolForUnixDomainSocket` test was flaky in
some situations due to the exception:

```
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@4c013e00[Not completed, task = java.util.concurrent.Executors#RunnableAdapter@53cbe68c[Wrapped task = org.neo4j.bolt.protocol.common.connector.connection.AtomicSchedulingConnection##Lambda/0x0000009000c1fad0@4e3a4810]] rejected from java.util.concurrent.ThreadPoolExecutor@309bcbc7[Running, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
```

The issue is resolved by giving the pool slightly more headroom,
increasing the max size from 1 to 2. This does not change the goal of
the test, but avoids unnecessary contention.

The regular sockets thread pool max size was decreased from 2 to 1,
since test saturation of this resource is achieved with a single thread.
This also fixes the assertion.

As a result of the configuration changes, other tests have been adjusted
accordingly.